### ISSUE TITLE
Method not found running on NetCoreApp3.1

### ISSUE THREAD

**Issue by chriswill** [MisinformedDNA/AzureFunctions.AspNetConfiguration#2]
Method not found: 'Microsoft.Extensions.Hosting.IHostingEnvironment Microsoft.Extensions.Hosting.HostBuilderContext.get_HostingEnvironment()'.

This is a deprecation/shift that took place in NetCoreApp3.1

For example:
https://andrewlock.net/ihostingenvironment-vs-ihost-environment-obsolete-types-in-net-core-3/

**Comment by chriswill** [comment]
I'll whip up a PR

**Comment by chriswill** [comment]
I have this working for netcoreapp3.1 but this then breaks your previous netcoreapp2.1 implementation.  The references required to support this appear to be so different as to not support simultaneous 2.1/3.1 support.  It may require a separate AzureFunctions.AspNetConfiguration assembly.

You can look at my repo at https://github.com/chriswill/AzureFunctions.AspNetConfiguration to see my wip, but I don't think I'll be able to submit a workable PR that supports both platforms.

**Comment by MisinformedDNA** [comment]
I [commited](https://github.com/MisinformedDNA/AzureFunctions.AspNetConfiguration/commit/218ab703712e2d651217884c47170bd90d0a97c6) changes for Functions v3 and have published it to [NuGet](https://www.nuget.org/packages/AzureFunctions.AspNetConfiguration/2.0.0-beta). Let me know if you find any issues.
