### ISSUE TITLE
Reading local files at scale with consumption plan

### ISSUE THREAD

**Issue by gorillapower** [MisinformedDNA/AzureFunctions.AspNetConfiguration#5]
Thanks for the great library. I wanted to ask if you have had success with using this approach (accessing local files) on the Azure Functions Consumption Plan model? I came across this gotcha here - https://github.com/MicrosoftDocs/azure-docs/issues/55946 and wondered if I should continue down the reading local files path.

**Comment by MisinformedDNA** [comment]
(Sorry, I just saw this.) 

I use the library with a consumption plan without any problem. The core issue is specifically related to trigger connections.

> Values read from these files related to trigger connections aren't available

So, for those cases, I have to push those settings to the FuncApp's appsettings.

Hope that helps.
